import test from 'node:test';
import assert from 'node:assert/strict';
import {MediaBank} from '../src/media.js';
class ImageStub{constructor(){this.naturalWidth=640;this.naturalHeight=360;this.listeners={};}addEventListener(type,fn){this.listeners[type]=fn;}}
class VideoStub extends ImageStub{constructor(){super();this.videoWidth=640;this.videoHeight=360;this.readyState=2;this.currentTime=8;this.paused=true;this.plays=0;}setAttribute(){}removeAttribute(name){delete this[name];}load(){this.reloaded=true;}play(){this.plays++;this.paused=false;return this.blockPlayback?Promise.reject(new Error('autoplay denied')):Promise.resolve();}pause(){this.paused=true;}}
function withMedia(run){const values={document:{createElement:()=>new VideoStub()},Image:ImageStub},old={};for(const[k,v]of Object.entries(values)){old[k]=Object.getOwnPropertyDescriptor(globalThis,k);Object.defineProperty(globalThis,k,{value:v,configurable:true});}try{return run(new MediaBank());}finally{for(const key of Object.keys(values)){if(old[key])Object.defineProperty(globalThis,key,old[key]);else delete globalThis[key];}}}
function context(){return{images:[],labels:[],fillRect(){},drawImage(image){this.images.push(image);},fillText(label){this.labels.push(label);}};}
test('supplied clips start muted, looping and inline',()=>withMedia(bank=>{bank.set('a','./media/Input%20A.mp4','video','Input A.mp4');const video=bank.items.a.el;assert.equal(video.muted,true);assert.equal(video.loop,true);assert.equal(video.playsInline,true);assert.equal(video.plays,1);}));
test('only current program video can be audible',()=>withMedia(bank=>{bank.set('a','a.mp4','video','Input A.mp4');bank.set('b','b.mp4','video','Input B.mp4');bank.audio=true;bank.route({output:'a'});assert.equal(bank.items.a.el.muted,false);assert.equal(bank.items.b.el.muted,true);bank.route({output:'b'});assert.equal(bank.items.a.el.muted,true);assert.equal(bank.items.b.el.muted,false);bank.route({output:'rescue'});assert.equal(bank.items.a.el.muted,true);assert.equal(bank.items.b.el.muted,true);}));
test('break restarts when routed explicitly',()=>withMedia(bank=>{bank.set('break','Break.mp4','video','Break.mp4');bank.route({output:'break'},true);assert.equal(bank.items.break.el.currentTime,0);}));
test('hidden-page pause and resume cover every video',()=>withMedia(bank=>{bank.set('a','a.mp4','video','Input A.mp4');bank.set('b','b.mp4','video','Input B.mp4');bank.pause();assert.ok(Object.values(bank.items).every(item=>item.el.paused));bank.prime();assert.ok(Object.values(bank.items).every(item=>!item.el.paused&&item.el.plays===2));}));
test('loading videos show labeled posters, then actual decoded frames',()=>withMedia(bank=>{bank.set('a','a.mp4','video','Input A.mp4',false,'a.jpg');const item=bank.items.a;item.el.readyState=0;let ctx=context();bank.draw(ctx,'a',0,0,640,360);assert.equal(ctx.images[0],item.poster);assert.ok(ctx.labels.includes('VIDEO POSTER · LOADING'));item.el.readyState=2;ctx=context();bank.draw(ctx,'a',0,0,640,360);assert.equal(ctx.images[0],item.el);assert.equal(ctx.labels.length,0);}));
test('bad video produces an error slate, not a misleading old poster',()=>withMedia(bank=>{bank.set('a','a.mp4','video','Input A.mp4',false,'a.jpg');const item=bank.items.a;item.el.listeners.error();const ctx=context();bank.draw(ctx,'a',0,0,640,360);assert.equal(ctx.images.length,0);assert.ok(ctx.labels.some(label=>label.includes('MEDIA UNAVAILABLE')));}));
test('replacing a clip stops and detaches the previous video',()=>withMedia(bank=>{bank.set('a','old.mp4','video','Input A.mp4');const old=bank.items.a.el;bank.set('a','new.mp4','video','Input A.mp4');assert.equal(old.paused,true);assert.equal(old.src,undefined);assert.equal(old.reloaded,true);assert.equal(bank.items.a.el.src,'new.mp4');}));
