import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../vendor/three.module.js';
import {Viewer,viewerCamera,referenceSphere,desktopFov,displayPixelRatio,fittedPixelRatio} from '../src/viewer.js';
import {createModel,CONTROLS} from '../src/model.js';
function fakeCanvas(){return {width:1024,height:576,getContext(){return {fillRect(){},fillText(){},strokeRect(){}};}};}
function withViewer(run,{dpr=1}={}){
  const values={document:{createElement:fakeCanvas},devicePixelRatio:dpr,innerWidth:1280};const old={};for(const[k,v]of Object.entries(values)){old[k]=Object.getOwnPropertyDescriptor(globalThis,k);Object.defineProperty(globalThis,k,{value:v,configurable:true});}
  const renderer={ratio:1,calls:[],setPixelRatio(n){this.ratio=n;},getPixelRatio(){return this.ratio;},setSize(w,h){this.size=[w,h];},setRenderTarget(t){this.target=t;},setViewport(){},render(s,c){this.calls.push({scene:s,camera:c,target:this.target});}};
  try{const v=new Viewer({}, {tv:fakeCanvas(),left:fakeCanvas(),right:fakeCanvas()},createModel().state,renderer);v.resize(1200,650);v.scene.updateMatrixWorld(true);return run(v,renderer);}finally{for(const key of Object.keys(values)){if(old[key])Object.defineProperty(globalThis,key,old[key]);else delete globalThis[key];}}
}
test('exactly one TV and two monitor surfaces',()=>withViewer(v=>{const ids=[];v.room.traverse(o=>{if(o.userData.screen)ids.push(o.userData.screen);});assert.deepEqual(ids.sort(),['left','right','tv']);}));
test('all six desk controls are visible and pickable from operator eye',()=>withViewer(v=>{for(const button of v.buttons.filter(b=>CONTROLS.some(control=>control.id===b.id))){v.camera.lookAt(button.face.getWorldPosition(new T.Vector3()));assert.equal(v.pick()?.action,button.id,button.id);}}));
test('headset exit and recenter remain accessible',()=>withViewer(v=>{v.setVR(true);v.scene.updateMatrixWorld(true);for(const id of ['exit','recenter']){const b=v.buttons.find(b=>b.id===id);v.camera.lookAt(b.face.getWorldPosition(new T.Vector3()));assert.equal(v.pick()?.action,id);}}));
test('stereo eye projections remain finite and parallel',()=>{const camera=viewerCamera();camera.aspect=2;camera.updateProjectionMatrix();camera.updateMatrixWorld();const stereo=new T.StereoCamera();stereo.aspect=.5;stereo.update(camera);assert.equal(camera.focus,Infinity);for(const c of [stereo.cameraL,stereo.cameraR])assert.ok(c.projectionMatrix.elements.every(Number.isFinite));assert.equal(stereo.cameraL.projectionMatrix.elements[8],0);assert.equal(stereo.cameraR.projectionMatrix.elements[8],0);});
test('headset renders two eyes then composite at full viewport',()=>withViewer((v,r)=>{v.setVR(true);v.resize(1200,650);v.render(.5);assert.equal(r.calls.length,3);assert.equal(r.calls[0].target,v.targets[0]);assert.equal(r.calls[1].target,v.targets[1]);assert.equal(r.calls[2].target,null);assert.equal(v.targets[0].width,600);assert.equal(v.targets[0].height,650);}));
test('headset starts at the full phone display density instead of a mobile DPR cap',()=>withViewer((v,r)=>{v.setVR(true);v.resize(844,390);assert.equal(r.ratio,3);assert.equal(v.targets[0].width,1266);assert.equal(v.targets[0].height,1170);assert.deepEqual(v.resolutionInfo(),{native:true,pixelRatio:3,eyeScale:1,outputWidth:2532,outputHeight:1170,eyeWidth:1266,eyeHeight:1170});},{dpr:3}));
test('adaptive eye buffers protect frame pacing without lowering the native output canvas',()=>withViewer((v,r)=>{v.setVR(true);v.resize(844,390);for(let frame=0;frame<220;frame++)v.noteFrame(1/30);assert.ok(v.eyeScale<1);assert.ok(v.eyeScale>=.7);assert.equal(r.ratio,3);assert.equal(v.resolutionInfo().outputWidth,2532);assert.ok(v.targets[0].width<1266);},{dpr:3}));
test('lighter graphics is explicit and returning to quality mode restores native DPR',()=>withViewer((v,r)=>{v.setVR(true);v.setQuality(true);assert.equal(r.ratio,1);v.setQuality(false);assert.equal(r.ratio,3);},{dpr:3}));
test('pixel-ratio helpers reject invalid DPR and respect GPU dimensions',()=>{assert.equal(displayPixelRatio(NaN),1);assert.equal(displayPixelRatio(3),3);assert.equal(fittedPixelRatio(3,1000,600,2000,1600),2);});
test('return to mono hides VR controls and uses one render',()=>withViewer((v,r)=>{v.setVR(true);v.setVR(false);v.render(0);assert.equal(v.utilities.visible,false);assert.equal(v.cursor.visible,false);assert.equal(r.calls.length,1);}));
test('original panorama has inward-facing geometry, with front seam and rear door correctly oriented',()=>{const camera=viewerCamera(),sphere=referenceSphere(new T.Texture(),camera.position);sphere.visible=true;sphere.updateMatrixWorld(true);for(const d of [new T.Vector3(0,0,-1),new T.Vector3(0,0,1),new T.Vector3(1,0,0),new T.Vector3(-1,0,0)]){const hits=new T.Raycaster(camera.position,d).intersectObject(sphere);assert.ok(hits.length,'inside of sphere must be visible');assert.ok(hits[0].distance>24&&hits[0].distance<26);if(d.z===-1)assert.ok(hits[0].uv.x<.001||hits[0].uv.x>.999);if(d.z===1)assert.ok(Math.abs(hits[0].uv.x-.5)<.001);}});
test('an unavailable panorama cannot replace the working studio',()=>withViewer(v=>{assert.equal(v.setEnvironment('photo'),false);assert.equal(v.environment,'studio');assert.equal(v.room.visible,true);}));
test('photo view is explicitly static and can always return to the live room',()=>withViewer(v=>{v.photoReady=true;v.photo=referenceSphere(new T.Texture(),v.camera.position);assert.equal(v.setEnvironment('photo'),true);assert.equal(v.room.visible,false);assert.equal(v.photo.visible,true);assert.equal(v.pick(),null);assert.equal(v.setEnvironment('studio'),true);assert.equal(v.room.visible,true);assert.equal(v.photo.visible,false);}));
test('VR status strip cannot mask any monitor picture',()=>withViewer(v=>{v.setVR(true);v.message('Now live — Input A');v.render(0);v.scene.updateMatrixWorld(true);const origin=v.camera.getWorldPosition(new T.Vector3());for(const surface of Object.values(v.surfaces)){const {width,height}=surface.geometry.parameters;for(let row=0;row<=8;row++)for(let column=0;column<=8;column++){const point=surface.localToWorld(new T.Vector3((column/8-.5)*width*.999,(row/8-.5)*height*.999,0));const ray=new T.Raycaster(origin,point.clone().sub(origin).normalize());const hit=ray.intersectObject(v.feedback)[0];assert.ok(!hit||hit.distance>origin.distanceTo(point),surface.name);}}}));
test('portrait FOV adapts and the three surfaces still frame',()=>withViewer(v=>{v.resize(360,570);v.camera.updateMatrixWorld();assert.ok(desktopFov(360/570)>desktopFov(16/9));for(const screen of Object.values(v.surfaces)){const {width,height}=screen.geometry.parameters;for(const x of [-width/2,width/2])for(const y of [-height/2,height/2]){const p=screen.localToWorld(new T.Vector3(x,y,0)).project(v.camera);assert.ok(Math.abs(p.x)<1&&Math.abs(p.y)<1,screen.name);}}}));
